baseline: Thoughts of a Scouse Software Developer
theme: hyde
output:
  formats:
    - name: netlify_redirects
      mediatype: text/plain
      extension: ""
keywords: Cecil, Static Site Generator, SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
postprocess:
  enabled: true
title: Lawrence Pickford
description: Thoughts of a Scouse Software Developer
baseurl: /
canonicalurl: true
virtualpages:
  - path: admin
    title: Content Manager (Netlify CMS)
    layout: admin/index
    output: html
  - path: _redirects
    output: netlify_redirects
